name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve SpotSpoof CLI!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added or changed?
      placeholder: Short, clear description.
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Who benefits and how would it be used?
    validations:
      required: true
  - type: textarea
    id: proposed
    attributes:
      label: Proposed Solution
      description: Any ideas for implementation or behavior.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you’ve tried or considered.
    validations:
      required: false
