name: Question
description: Ask a question about usage or integration.
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question and include relevant context.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Environment, commands used, or integration details.
    validations:
      required: false
